export const activities = [
    {
      sno: '01',
      name: 'Cyber Security Club Introduction to Burp Suite',
      clubname: 'Cyber Security Club',
      date: '25th September 23',
      time: '5:40 PM - 7:10 PM',
      venue: 'Sac Hall',
    },
    {
      sno: '02',
      name: 'Angular JS',
      clubname: 'ZeroOne Code Club',
      date: '25th September',
      time: '5.30 - 7.30 pm',
      venue: 'M002A',
    },
    {
      sno: '03',
      name: 'React Router DOM V6',
      clubname: 'ZeroOne Code Club',
      date: '26th September',
      time: '5.30 - 7.30 pm',
      venue: 'M002A',
    },
    {
      sno: '04',
      name: 'Narthana Dance Club Tremendous Tuesday',
      clubname: 'Narthana Dance Club',
      date: '26th September 2023',
      time: '5:00 PM - 7:00 PM',
      venue: 'New Seminar Hall',
    },
    {
      sno: '05',
      name: 'El Comicos Stand Up Show',
      clubname: 'El Comicos',
      date: '26th September 2023',
      time: '6:00 PM - 7:00 PM',
      venue: 'Jasmine Hall',
    },
    {
      sno: '06',
      name: 'Bash Scripting for Developers',
      clubname: 'ZeroOne Code Club',
      date: '27th September',
      time: '5.30 - 7.30 pm',
      venue: 'Jasmine Hall',
    },
    {
      sno: '08',
      name: 'KL FILM CLUB MASTERCRAFT',
      clubname: 'KL FILM CLUB',
      date: '27th September 2023',
      time: '5:00 PM - 7:00 PM',
      venue: 'NEW SEMINAR HALL',
    },
    {
        sno: '09',
        name: 'Mobile E-Sports Club Mobile Sports Tournament',
        clubname: 'Mobile E-Sports Club',
        date: '27th September 2223',
        time: '5:40 PM - 7:00 PM',
        venue: 'Sac Hall',
    },
    {
      sno: '10',
      name: 'SVR "EcoGas Harvest"',
      clubname: 'SVR',
      date: '27th September 2223',
      time: '9:00 AM - 5:00 PM',
      venue: 'Morusumilli thanda',
    },
    {
      sno: '11',
      name: 'FUSION-DANCE CLUB RETRO HITS',
      clubname: 'FUSION-DANCE CLUB',
      date: '27th September 2023',
      time: '5:00 PM - 7:00 PM',
      venue: 'NEW SEMINAR HALL',
    },
    {
      sno: '12',
      name: 'Versatales Club Senario Ink Battle',
      clubname: 'Versatales',
      date: '28th September 2023',
      time: '3:30 PM - 7:30 PM',
      venue: 'Rose Hall',
    },
    {
      sno: '13',
      name: 'KUTUMB WordWeave',
      clubname: 'KUTUMB',
      date: '29th September 2023',
      time: '5:30 PM - 7:10 PM',
      venue: 'SAC hall',
    },
    {
      sno: '14',
      name: 'Web Development Session',
      clubname: 'WebApps Club',
      date: '29th September 2023',
      time: '6:00 PM - 7:00 PM',
      venue: 'Jasmine Hall',
    },
    {
      sno: '15',
      name: 'Agriculture Club Orientation and Hydroponics chapter one',
      clubname: 'Agriculture Club',
      date: '29th September 2023',
      time: '6:00 PM - 7:00 PM',
      venue: 'Jasmine Hall',
    },
    {
        sno: '16',
        name: 'UI/UX Designing',
        clubname: 'WebApps Club',
        date: '29th September 2023',
        time: '6:00 PM - 7:00 PM',
        venue: 'Jasmine Hall',
      },
      {
        sno: '17',
        name: 'App Development Session',
        clubname: 'WebApps Club',
        date: '29th September 2023',
        time: '6:00 PM - 7:00 PM',
        venue: 'Jasmine Hall',
      },
    {
      sno: '18',
      name: 'Yuva Tourism Club Travel for Life Webinar',
      clubname: 'Yuva Tourism Club',
      date: '29th September 2023',
      time: '5:40 PM - 7:20 PM',
      venue: 'Any Room',
    },
    {
      sno: '19',
      name: 'Electoral literacy club session on why to vote',
      clubname: 'Electoral literacy club',
      date: '30th September 2023',
      time: '5.30 PM - 7.30 PM',
      venue: 'Sac Hall',
    },
    {
      sno: '20',
      name: 'Ohana Charity Outreach',
      clubname: 'Ohana',
      date: '30th September 2023',
      time: '3:00 PM - 6:00 PM',
      venue: 'Guntur',
    },
  ];


 export const projects = [ 
    {
        sno: '01',
        name: 'ZeroOne website in Next.js',
        clubname: 'ZeroOne Code Club',
        resource: 'https://github.com/DeepakReddyG/cyd-nextjs',
        description: 'The primary aim of this project is to develop a cutting-edge web application for ZeroOne club. Leveraging the advanced capabilities of Next.js, an enhanced version of React, this project places significant emphasis on crafting an exceptional user interface. The application is intended to cater not only to the club members but also to other users seeking an engaging and seamless experience.',
    },
    {
        sno: '02',
        name: 'ZeroOne Learning',
        clubname: 'ZeroOne Code Club',
        resource: 'https://github.com/saitadikonda99/ZeroOne-Learning',
        description: 'ZeroOne Learning E-Portal is a user-friendly website designed to facilitate beginner-level C programming education. Our platform offers a seamless learning experience, providing easy-to-follow tutorials and interactive exercises for mastering C programming concepts. With a focus on simplicity and effectiveness, aspiring programmers can quickly grasp fundamental coding skills and embark on their programming journey confidently. Join us at ZeroOne Learning E-Portal and unlock your potential in C programming!',
    },
    {
        sno: '02',
        name: 'ZeroOne Learning',
        clubname: 'ZeroOne Code Club',
        resource: 'https://github.com/saitadikonda99/ZeroOne-Learning',
        description: 'ZeroOne Learning E-Portal is a user-friendly website designed to facilitate beginner-level C programming education. Our platform offers a seamless learning experience, providing easy-to-follow tutorials and interactive exercises for mastering C programming concepts. With a focus on simplicity and effectiveness, aspiring programmers can quickly grasp fundamental coding skills and embark on their programming journey confidently. Join us at ZeroOne Learning E-Portal and unlock your potential in C programming!',
    },
    {
        sno: '03',
        name: 'ZeroOne ERP',
        clubname: 'ZeroOne Code Club',
        resource: 'https://github.com/DeepakReddyG/clubRegistrations',
        description: 'ZeroOne Learning E-Portal is a user-friendly website designed to facilitate beginner-level C programming education. Our platform offers a seamless learning experience, providing easy-to-follow tutorials and interactive exercises for mastering C programming concepts. With a focus on simplicity and effectiveness, aspiring programmers can quickly grasp fundamental coding skills and embark on their programming journey confidently. Join us at ZeroOne Learning E-Portal and unlock your potential in C programming!',
    },
    {
        sno: '04',
        name: 'SAC Admin Panel',
        clubname: 'ZeroOne Code Club',
        resource: 'https://github.com/DeepakReddyG/sac-dashboard',
        description: 'ZeroOne Learning E-Portal is a user-friendly website designed to facilitate beginner-level C programming education. Our platform offers a seamless learning experience, providing easy-to-follow tutorials and interactive exercises for mastering C programming concepts. With a focus on simplicity and effectiveness, aspiring programmers can quickly grasp fundamental coding skills and embark on their programming journey confidently. Join us at ZeroOne Learning E-Portal and unlock your potential in C programming!',
    },
    {
        sno: '05',
        name: 'SAC Website',
        clubname: 'ZeroOne Code Club',
        resource: 'https://github.com/Hallos74/DotFiles',
        description: 'ZeroOne Learning E-Portal is a user-friendly website designed to facilitate beginner-level C programming education. Our platform offers a seamless learning experience, providing easy-to-follow tutorials and interactive exercises for mastering C programming concepts. With a focus on simplicity and effectiveness, aspiring programmers can quickly grasp fundamental coding skills and embark on their programming journey confidently. Join us at ZeroOne Learning E-Portal and unlock your potential in C programming!',
    },
    {
        sno: '06',
        name: 'Customizing ArchLinux ',
        clubname: 'ZeroOne Code Club',
        resource: 'https://github.com/DeepakReddyG/Zvim',
        description: 'ZeroOne Learning E-Portal is a user-friendly website designed to facilitate beginner-level C programming education. Our platform offers a seamless learning experience, providing easy-to-follow tutorials and interactive exercises for mastering C programming concepts. With a focus on simplicity and effectiveness, aspiring programmers can quickly grasp fundamental coding skills and embark on their programming journey confidently. Join us at ZeroOne Learning E-Portal and unlock your potential in C programming!',
    },
    {
        sno: '07',
        name: 'ZVIM',
        clubname: 'ZeroOne Code Club',
        resource: 'https://github.com/DeepakReddyG/Zvim',
        description: 'ZeroOne Learning E-Portal is a user-friendly website designed to facilitate beginner-level C programming education. Our platform offers a seamless learning experience, providing easy-to-follow tutorials and interactive exercises for mastering C programming concepts. With a focus on simplicity and effectiveness, aspiring programmers can quickly grasp fundamental coding skills and embark on their programming journey confidently. Join us at ZeroOne Learning E-Portal and unlock your potential in C programming!',
    },
    
    ];


    
